# Generated by Django 4.2.8 on 2023-12-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0002_remove_post_user_remove_vote_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
